### PR TITLE
(Closes #27) Add install queue.

### LINKED ISSUE #27: Add install queue to ContentInventory
This would allow triggered installs to persist across launches so they don't get lost. It would also allow course-grained install priority as well as retrying of failed installs.

I'm imagining it would have three "states" or "buckets": errored, regular install (or high priority), and background install (or low priority).

### PR DESCRIPTION
**Pull request by nickmshelley**

### CODE REVIEW

File: LDSContent/ContentInventory.swift [hunk 1]
```diff
@@ -135,6 +143,60 @@ extension ContentInventory {
...
+    
+    func installingItemIDs() -> [Int64] {
+        do {
+            return try db.prepare(InstallQueueTable.table.select(InstallQueueTable.itemID)).map { $0[InstallQueueTable.itemID] }
+        } catch {
+            return []
+        }
+    }
+    
+    func setInstalling(itemID itemID: Int64) throws {
```
Comment (hiltonc) [inline LDSContent/ContentInventory.swift]: This is all subjective, but suggested renames for clarity and consistency:

setInstalling -> addToInstallQueue
removeFromQueue -> removeFromInstallQueue
setErrored, removeErrored -> setErrored(errored: Bool, itemID: Int64)

For the last two, if you'd prefer separate functions, I'd prefer to see better symmetry in their names. The opposite of remove is usually add, but I don't know if I like that.

File: LDSContent/ContentController.swift [hunk 2]
```diff
@@ -265,6 +288,14 @@ public class ContentController {
         return contentInventory.installedItemIDs()
     }
     
+    public func installingItemIDs() -> [Int64] {
```
Comment (hiltonc) [inline LDSContent/ContentController.swift]: I think we'll need observer sets for these also, but if you don't need that immediately we can do it later.

File: LDSContent/ContentInventory.swift (hunk 1 above)
Comment (nickmshelley) [inline LDSContent/ContentInventory.swift]: I like the suggestions, I wasn't really happy about the naming but couldn't think of anything better at the moment.

File: LDSContent/ContentController.swift (hunk 2 above)
Comment (nickmshelley) [inline LDSContent/ContentController.swift]: The only place I think GL needs this info is on startup so it can resume downloads. I can't think of a situation where it would need to observe this. So yeah, I'd prefer to add it later if/when we need it.

Comment (hiltonc) [inline LDSContent/ContentController.swift]: I was thinking for showing which items are pending download. I guess that's handled elsewhere?

File: LDSContent/ContentInventory.swift [hunk 3]
```diff
@@ -135,6 +143,61 @@ extension ContentInventory {
...
+    
+    func erroredItemIDs() -> [Int64] {
+        do {
+            return try db.prepare(ErroredInstallTable.table.select(ErroredInstallTable.itemID)).map { $0[ErroredInstallTable.itemID] }
+        } catch {
+            return []
+        }
+    }
+    
+    func setErrored(errored errored: Bool, itemID: Int64) throws {
```
Comment (hiltonc) [inline LDSContent/ContentInventory.swift]: No need to name the first argument.

**Comment by hiltonc** [comment]
👍  although setErrored(errored: is a little redundant.

File: LDSContent/ContentController.swift (hunk 2 above)
Comment (nickmshelley) [inline LDSContent/ContentController.swift]: Well you pull to get which items in your view are pending, then observe itemPackageInstall for changes. Although that wouldn't handle errored downloads... Maybe we change `itemPackageInstallObservers` to include a `Bool` indicating success?

Comment (nickmshelley) [inline LDSContent/ContentController.swift]: The purpose of this PR was to allow install to continue or retry on launch, so I'd still prefer to figure this other part out later if that's ok. It was still a good point to bring up.

Comment (hiltonc) [inline LDSContent/ContentController.swift]: Tallyho!

File: LDSContent/ContentInventory.swift (hunk 3 above)
Comment (nickmshelley) [inline LDSContent/ContentInventory.swift]: Good point. Habit I guess.

**Comment by hiltonc** [comment]
👍 👍
